-- Base inicial gerada da planilha de referência.
insert into public.gratificacoes(cenario_id,tipo_id,unidade_sigla,unidade_nome,servidor_nome,com_vinculo,situacao,legacy_order) values
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-04'),'GABPRES','SECRETARIA-GERAL DA PRESIDÊNCIA','Servidor 001',true,'ANTIGA',1),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-04'),'DGERAL','DIRETORIA-GERAL','Servidor 002',true,'ANTIGA',2),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VICE-PRES','SECRETARIA DA CORREGEDORIA REGIONAL','Servidor 003',true,'ANTIGA',3),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'GABCN','ASS. JURÍDICA DO GAB. DES. FRANCISCO JOSÉ DE CARVALHO NETO','Servidor 004',true,'ANTIGA',4),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'GABGC','ASS. JURÍDICA DO GAB. DES. GÉRSON DE OLIVEIRA COSTA FILHO','Servidor 005',true,'ANTIGA',5),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'GABES','ASS. JURÍDICA DO GAB. DES. JOSÉ EVANDRO DE SOUSA','Servidor 006',true,'ANTIGA',6),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'GABMA','ASS. JURÍDICA DO GAB. DESA. MÁRCIA ANDREA FARIAS DA SILVA','Servidor 007',false,'ANTIGA',7),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'GABIE','ASS. JURÍDICA DO GAB. DESA. ILKA ESDRA SILVA ARAÚJO','Servidor 008',true,'ANTIGA',8),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'GABLC','ASS. JURÍDICA DO GAB. DES. LUIZ COSMO DA SILVA JÚNIOR','Servidor 009',true,'ANTIGA',9),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'GABJF','ASS. JURÍDICA DO GAB. DES. JAMES MAGNO ARAÚJO FARIAS','Servidor 010',false,'ANTIGA',10),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'GABSC','ASS. JURÍDICA DO GAB. DESA. SOLANGE CRISTINA PASSOS DE CASTRO','Servidor 011',false,'ANTIGA',11),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'SECPLENO','SECRETARIA DO TRIBUNAL PLENO','Servidor 012',true,'ANTIGA',12),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'EJUD','SECRETARIA DA ESCOLA JUDICIAL','Servidor 013',true,'ANTIGA',13),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'CGGE','SECRETARIA DE GOVERNANÇA E GESTÃO ESTRATÉGICA','Servidor 014',true,'ANTIGA',14),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'CTIC','SECRETARIA DE TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO','Servidor 015',true,'ANTIGA',15),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'CCI','SECRETARIA DE AUDITORIA','Servidor 016',true,'ANTIGA',16),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'CGP','SECRETARIA DE GESTÃO DE PESSOAS','Servidor 017',true,'NOVA',17),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'SOF','SECRETARIA DE ORÇAMENTO E FINANÇAS','Servidor 018',true,'ANTIGA',18),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VT1SLZ','1ª VARA DO TRABALHO DE SÃO LUÍS','Servidor 019',true,'ANTIGA',19),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VT2SLZ','2ª VARA DO TRABALHO DE SÃO LUÍS','Servidor 020',true,'ANTIGA',20),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VT3SLZ','3ª VARA DO TRABALHO DE SÃO LUÍS','Servidor 021',true,'ANTIGA',21),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VT4SLZ','4ª VARA DO TRABALHO DE SÃO LUÍS','Servidor 022',true,'ANTIGA',22),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VT5SLZ','5ª VARA DO TRABALHO DE SÃO LUÍS','Servidor 023',false,'ANTIGA',23),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VT6SLZ','6ª VARA DO TRABALHO DE SÃO LUÍS','Servidor 024',false,'ANTIGA',24),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VT7SLZ','7ª VARA DO TRABALHO DE SÃO LUÍS','Servidor 025',false,'ANTIGA',25),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VT1IMPZ','1ª VARA DO TRABALHO DE IMPERATRIZ','Servidor 026',true,'ANTIGA',26),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'V2IMPZ','2ª VARA DO TRABALHO DE IMPERATRIZ','Servidor 027',true,'ANTIGA',27),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTACAI','VARA DO TRABALHO DE AÇAILÂNDIA','Servidor 028',true,'ANTIGA',28),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTBAC','VARA DO TRABALHO DE BACABAL','Servidor 029',true,'ANTIGA',29),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTBAL','VARA DO TRABALHO DE BALSAS','Servidor 030',true,'ANTIGA',30),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTBDC','VARA DO TRABALHO DE BARRA DO CORDA','Servidor 031',true,'ANTIGA',31),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTBAR','VARA DO TRABALHO DE BARREIRINHAS','Servidor 032',true,'ANTIGA',32),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTCAX','VARA DO TRABALHO DE CAXIAS','Servidor 033',true,'ANTIGA',33),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTCHAP','VARA DO TRABALHO DE CHAPADINHA','Servidor 034',true,'ANTIGA',34),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTESTR','VARA DO TRABALHO DE ESTREITO','Servidor 035',true,'ANTIGA',35),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTPEDR','VARA DO TRABALHO DE PEDREIRAS','Servidor 036',true,'ANTIGA',36),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTPHO','VARA DO TRABALHO DE PINHEIRO','Servidor 037',true,'ANTIGA',37),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTPDUT','VARA DO TRABALHO DE PRESIDENTE DUTRA','Servidor 038',true,'ANTIGA',38),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTSINES','VARA DO TRABALHO DE SANTA INÊS','Servidor 039',true,'ANTIGA',39),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTSJDP','VARA DO TRABALHO DE SÃO JOÃO DOS PATOS',null,true,'ANTIGA',40),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-03'),'VTTIMON','VARA DO TRABALHO DE TIMON','Servidor 041',true,'ANTIGA',41),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABCN','ASS. ADMINISTRATIVA DO GAB. DES. FRANCISCO JOSÉ DE CARVALHO NETO','Servidor 042',false,'NOVA',42),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABGC','ASS. ADMINISTRATIVA DO GAB. DES. GÉRSON DE OLIVEIRA COSTA FILHO','Servidor 043',false,'NOVA',43),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABES','ASS. ADMINISTRATIVA DO DES. JOSÉ EVANDRO DE SOUSA','Servidor 044',true,'NOVA',44),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABMA','ASS. ADMINISTRATIVA DO GAB. DESA. MÁRCIA ANDREA FARIAS DA SILVA','Servidor 045',true,'NOVA',45),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABIE','ASS. ADMINISTRATIVA DO GAB. DESA. ILKA ESDRA SILVA ARAÚJO','Servidor 046',true,'NOVA',46),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABLC','ASS. ADMINISTRATIVA DO GAB. DES. LUIZ COSMO DA SILVA JÚNIOR','Servidor 047',true,'NOVA',47),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABJF','ASS. ADMINISTRATIVA DO GAB. DES. JAMES MAGNO ARAÚJO FARIAS','Servidor 048',false,'NOVA',48),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABSC','ASS. ADMINISTRATIVA DO GAB. DESA. SOLANGE CRISTINA PASSOS DE CASTRO','Servidor 049',false,'NOVA',49),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'GABPRES','COORDENADORIA DE PRECATÓRIOS','Servidor 050',true,'ANTIGA',50),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'DGERAL','ASS. ADMINISTRATIVA DA DIRETORIA-GERAL','Servidor 051',true,'ANTIGA',51),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'DSG','COORDENADORIA DE SERVIÇOS GERAIS','Servidor 052',true,'ANTIGA',52),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'CML','COORDENADORIA DE MATERIAL E LOGÍSTICA','Servidor 053',true,'ANTIGA',53),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'SECADMIN','COORDENADORIA DE ADMINISTRAÇÃO E GESTÃO NEGOCIAL','Servidor 054',true,'ANTIGA',54),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-02'),'DGERAL','COORDENADORIA DE ASSESSORAMENTO JURÍDICO','Servidor 055',true,'NOVA',55),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','ASS. ESPECIAL DO GABINETE DA PRESIDÊNCIA','Servidor 056',true,'NOVA',56),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','ASS. ADMINISTRATIVA DO GABINETE DA PRESIDÊNCIA','Servidor 057',true,'ANTIGA',57),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','DIVISÃO DE CERIMONIAL','Servidor 058',true,'NOVA',58),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'CGGE','DIVISÃO DE ESTATÍSTICA','Servidor 059',true,'NOVA',59),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'CTIC','DIVISÃO DE DESENVOLVIMENTO E SISTEMAS NACIONAIS','Servidor 060',true,'NOVA',60),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'CTIC','DIVISÃO DE INFRAESTRUTURA E SEGURANÇA DA INFORMAÇÃO','Servidor 061',true,'NOVA',61),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','DIVISÃO DE POLÍCIA JUDICIAL','Servidor 062',true,'NOVA',62),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','DIVISÃO DE ASSESSORIA DE COMUNICAÇÃO SOCIAL','Servidor 063',false,'NOVA',63),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'CRJA','DIVISÃO DE COORDENAÇÃO JUDICIÁRIA, RECURSOS E PRECEDENTES','Servidor 064',true,'ANTIGA',64),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'DGERAL','ASSESSORIA ESPECIAL DO GAB. DA VICE-PRESIDÊNCIA','Servidor 065',true,'ANTIGA',65),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'DGERAL','DIVISÃO DE GOVERNANÇA DE CONTRATAÇÕES E DE OBRAS','Servidor 066',true,'NOVA',66),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'CGP','DIVISÃO DE FOLHA DE PAGAMENTO','Servidor 067',true,'NOVA',67),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'DGERAL','DIVISÃO DE ENGENHARIA E ARQUITETURA','Servidor 068',true,'NOVA',68),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','CENTRO JUD. MÉTODOS CONSENSUAIS - SÃO LUÍS','Servidor 069',true,'ANTIGA',69),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','CENTRO JUD. MÉTODOS CONSENSUAIS - IMPERATRIZ','Servidor 070',true,'NOVA',70),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','CENTRO JUD. MÉTODOS CONSENSUAIS - CAXIAS','Servidor 071',true,'NOVA',71),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','NÚCLEO PERM. MÉTODOS CONSENSUAIS DE SOLUÇÃO DE DISPUTAS','Servidor 072',true,'NOVA',72),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','ASS. DE GESTÃO DE EXPEDIENTE E ACOMPANHAMENTO PROCESSUAL','Servidor 073',true,'ANTIGA',73),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','ASS. DE CONTRATOS E NORMATIVOS INTERNOS','Servidor 074',false,'ANTIGA',74),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','DIVISÃO DE AQUISIÇÕES E CONTRATAÇÕES','Servidor 075',true,'ANTIGA',75),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'GABPRES','DIVISÃO DE RECURSO DE REVISTA','Servidor 076',true,'NOVA',76),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'SOF','DIVISÃO DE APOIO ORÇAMENTÁRIO FINANCEIRO E CONTÁBIL','Servidor 077',true,'NOVA',77),
((select id from public.cenarios where status='VIGENTE'),(select id from public.tipos_gratificacao where codigo='CJ-01'),'','ASSESSORIA DE PLANEJAMENTO E GESTÃO DA PREVIDÊNCIA','Servidor 078',true,'NOVA',78);

do $$ declare c integer; v numeric(14,4); begin
  select count(*),sum(case when com_vinculo then t.valor_com_vinculo else t.valor_integral end) into c,v
  from public.gratificacoes g join public.tipos_gratificacao t on t.id=g.tipo_id where g.ativo;
  if c <> 78 or v <> 821607.0825 then raise exception 'Falha de regressão: % registros, % pagos',c,v; end if;
end $$;
