import assert from "node:assert/strict";
import { readFile, access } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const html = await readFile(resolve(root, "index.html"), "utf8");
const refs = [...html.matchAll(/(?:src|href)="(\.\/[^"?#]+)(?:[?#][^"]*)?"/g)].map(match => match[1]);
for (const ref of refs) await access(resolve(root, ref.slice(2)));
const all = await Promise.all(["index.html","app.js","auth.js","presence.js","data-service.js","supabase-client.js","app-config.js","styles.css","reports.css","supabase-email-template-recovery.html","supabase-email-template-invite.html","supabase-setup.sql","supabase-admin-presence-migration.sql","supabase-access-ui-migration.sql","supabase-references-migration.sql","supabase-history-migration.sql","supabase-grant-delete-migration.sql","supabase-user-profile-migration.sql","supabase-seed.sql","supabase/functions/invite-user/index.ts","supabase/functions/delete-user/index.ts","supabase/functions/update-user/index.ts","supabase/functions/update-user/validation.js",".nojekyll",".github/workflows/pages.yml"].map(file => readFile(resolve(root,file),"utf8")));
const combined = all.join("\n");
assert.doesNotMatch(combined, /sb_secret_[a-zA-Z0-9_-]+/i);
assert.doesNotMatch(combined, /serviceRoleKey\s*:\s*["'][^"']+/i);
assert.doesNotMatch(combined, /eyJ[a-zA-Z0-9_-]{20,}\.[a-zA-Z0-9_-]{20,}\.[a-zA-Z0-9_-]{20,}/);
assert.match(await readFile(resolve(root,".github/workflows/pages.yml"),"utf8"), /actions\/deploy-pages@v4/);
const auth = await readFile(resolve(root, "auth.js"), "utf8");
const app = await readFile(resolve(root, "app.js"), "utf8");
const htmlIds = new Set([...html.matchAll(/\bid="([A-Za-z0-9_-]+)"/g)].map(match => match[1]));
const referencedIds = new Set([...app.matchAll(/\$\("#([A-Za-z0-9_-]+)"\)/g)].map(match => match[1]));
for (const id of referencedIds) assert.ok(htmlIds.has(id), `O seletor #${id} do JavaScript deve existir no HTML`);
assert.match(auth, /\.eq\("id",\s*session\.user\.id\)\s*\.single\(\)/s, "A consulta do perfil deve ficar restrita ao usuário autenticado");
assert.match(auth, /updateUser\(\{ password \}\)/, "A recuperação deve permitir cadastrar a nova senha");
assert.match(auth, /verifyOtp\(\{[\s\S]*type,/, "O código deve ser validado com o tipo do fluxo de acesso");
assert.match(auth, /\["invite", "recovery"\]\.includes\(type\)/, "Somente convite e recuperação podem validar códigos de acesso");
assert.match(html, /id="password-recovery-form"/, "A página deve conter o formulário de nova senha");
assert.match(html, /id="recovery-code-form"[\s\S]*autocomplete="one-time-code"/, "A página deve permitir validar manualmente o código de recuperação");
assert.match(html, /id="first-access"[\s\S]*Primeiro acesso \/ cadastrar senha/, "O login deve oferecer cadastro da primeira senha");
assert.match(html, /id="user-form"[\s\S]*name="role"/, "A administração deve conter cadastro de usuário e perfil");
assert.match(html, /id="user-form"[\s\S]*class="invite-submit"/, "O botão de convite deve ter estilo próprio de altura padronizada");
assert.match(await readFile(resolve(root, "styles.css"), "utf8"), /#user-form \.invite-submit\{align-self:flex-end\}/, "O botão de convite não deve esticar junto aos campos do formulário");
assert.doesNotMatch(html, /value="auditor"|data-role="[^"]*auditor/, "Auditor não deve existir nas opções nem na navegação");
assert.match(html, /data-view="auditoria" data-role="admin"/, "A Auditoria deve aparecer somente para Admin");
assert.match(html, /data-view="referencias" data-role="admin,gestor"/, "Referências deve aparecer somente para Admin e Gestor");
assert.match(html, /id="referencias"[\s\S]*id="references-form"[\s\S]*id="references-table"/, "A página Referências deve conter competência, parâmetros e tabela financeira");
assert.match(html, /id="grant-scenario"[\s\S]*id="report-scenario"/, "Quadro e relatório devem selecionar competências históricas");
assert.match(await readFile(resolve(root, "styles.css"), "utf8"), /#grant-scenario-status\{display:flex;align-self:stretch;align-items:center;justify-content:center;text-align:center\}/, "O indicador da competência deve centralizar seu conteúdo nos dois eixos");
assert.doesNotMatch(html, /id="csjt-previous-scenario"|id="csjt-current-scenario"/, "O Quadro CSJT direto não deve exibir seletores redundantes de competência");
assert.match(html, /id="report-compare-scenario"[\s\S]*id="report-comparison"/, "O relatório deve comparar duas competências por identidade histórica");
assert.match(html, /name="complete_data"/, "A competência deve declarar explicitamente se a base individualizada está completa");
assert.match(html, /name="orcamento_paradigma"[\s\S]*name="competencia"[\s\S]*name="activate"/, "Referências deve administrar orçamento, competência e vigência");
assert.match(html, /data-view="gratificacoes">Quadro de Gratificações</, "O menu deve usar o novo nome do quadro");
assert.match(html, /data-view="dashboard" class="active">Painel Geral/, "O menu deve apresentar Painel Geral");
assert.match(html, /id="page-title">Painel Geral/, "O título inicial deve apresentar Painel Geral");
assert.doesNotMatch(html, /Cenário vigente/i, "A frase Cenário vigente deve ser removida");
assert.match(html, /src="\.\/assets\/trt16-logo\.png"[^>]+alt="Justiça do Trabalho — TRT da 16ª Região \(MA\)"/, "O menu deve exibir a logo oficial do TRT da 16ª Região com texto alternativo");
assert.match(html, /class="brand"[\s\S]*Gestão de Gratificações[\s\S]*<\/div>\s*<nav/, "O topo do menu deve manter o nome Gestão de Gratificações");
assert.doesNotMatch(html, /Gestão institucional/i, "O topo do menu não deve exibir Gestão institucional");
assert.match(html, /\[hidden\]\s*\{\s*display:\s*none\s*!important\s*\}/, "Telas ocultas não podem ser reexibidas pelo CSS de layout");
assert.match(await readFile(resolve(root, "app.js"), "utf8"), /PASSWORD_RECOVERY[\s\S]*otp_expired|otp_expired[\s\S]*PASSWORD_RECOVERY/, "A aplicação deve tratar recuperação e links expirados");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /functions\.invoke\("invite-user"/, "O cadastro deve usar a função protegida de convite");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /functions\.invoke\("delete-user"/, "A exclusão deve usar uma função administrativa protegida");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /functions\.invoke\("update-user"/, "A edição deve usar uma função administrativa protegida");
assert.doesNotMatch(await readFile(resolve(root, "data-service.js"), "utf8"), /from\("profiles"\)\.update/, "O navegador não deve editar perfis diretamente");
assert.match(html, /id="online-users-table"[\s\S]*id="profiles-table"/, "A administração deve mostrar usuários online e perfis cadastrados");
assert.match(app, /data-field=\"nome\"[\s\S]*data-field=\"email\"[\s\S]*data-field=\"role\"[\s\S]*data-field=\"ativo\"/, "A administração deve permitir editar nome, e-mail, perfil e situação");
assert.match(app, /profile-row-dirty[\s\S]*Alterações ainda não salvas|Alterações não salvas[\s\S]*profile-row-dirty/, "Alterações pendentes devem ficar visíveis e não afetar a exclusão");
assert.match(app, /alterando o e-mail da própria conta[\s\S]*removerá um administrador ativo/, "Mudanças sensíveis devem exigir confirmação");
assert.match(app, /data-delete-profile[\s\S]*prompt\([\s\S]*profile\.email/, "A exclusão deve exigir confirmação pelo e-mail do usuário");
assert.match(html, /id="report-field-options"[\s\S]*id="report-active"|id="report-active"[\s\S]*id="report-field-options"/, "O relatório deve permitir escolher campos e incluir inativas");
assert.match(html, /id="show-custom-report"[\s\S]*id="show-csjt-report"/, "Relatório customizável e Quadro CSJT devem compartilhar o seletor de relatórios");
assert.match(html, /id="report-title"[\s\S]*id="report-group"[\s\S]*id="report-order"[\s\S]*id="report-direction"/, "O relatório deve permitir título, agrupamento e ordenação");
assert.match(html, /id="csjt-report-view"[\s\S]*id="csjt-sheet"/, "O Quadro CSJT deve existir como relatório próprio");
assert.doesNotMatch(html, /SIMULAÇÕES|Incremento efetivos/i, "O Quadro CSJT não deve reproduzir a simulação da página de referência");
assert.match(app, /summarizeCsjtPrevious\(previousTypes[\s\S]*summarize\(grantsForScenario\(current\?\.id\)/, "O Quadro CSJT deve manter a base anterior fixa e calcular a atual pelo snapshot");
assert.match(app, /csjtSection\("Situação Anterior \(30\/06\/2022\)"/, "O título histórico deve permanecer imutável");
assert.match(app, /Situação Posterior \(\$\{scenarioCompetence\(current\)\}\)/, "O Quadro CSJT deve denominar a segunda tabela como Situação Posterior");
assert.doesNotMatch(app, /Situação Atual \(\$\{scenarioCompetence\(current\)\}\)/, "O Quadro CSJT não deve manter o título Situação Atual");
assert.match(app, /match\(\/\^\(\\d\{4\}\)-\(\\d\{2\}\)\/[\s\S]*\$\{match\[2\]\}\/\$\{match\[1\]\}/, "Competências devem ser exibidas no formato mês/ano sem alterar o valor técnico");
const calc = await readFile(resolve(root, "calc.js"), "utf8");
assert.match(calc, /CSJT_PREVIOUS_COUNTS[\s\S]*"CJ-04", linked: 2, unlinked: 0[\s\S]*"CJ-03", linked: 32, unlinked: 4[\s\S]*"CJ-02", linked: 10, unlinked: 3[\s\S]*"CJ-01", linked: 0, unlinked: 0/, "As quantidades institucionais de 30/06/2022 devem permanecer fixas");
assert.match(calc, /summarizeCsjtPrevious\(types, budget\)[\s\S]*linkedAmount4\(type\)[\s\S]*decimal4\(type\.valor_integral\)/, "Os valores históricos devem ser recalculados pela competência financeira escolhida");
assert.match(await readFile(resolve(root, "reports.css"), "utf8"), /\.csjt-bottom[\s\S]*\.info-value[\s\S]*body\.printing-csjt/, "O Quadro CSJT deve manter os quadros inferiores e a impressão da referência");
assert.match(app, /updateNewGrantVisibility\(button\.dataset\.view\)/, "Nova gratificação deve acompanhar a seção ativa");
assert.match(app, /activeView === "gratificacoes"/, "Nova gratificação deve aparecer somente em Gratificações");
assert.match(app, /GRANT_SORT_FIELDS[\s\S]*tipo_codigo[\s\S]*servidor_nome[\s\S]*unidade_nome[\s\S]*unidade_sigla[\s\S]*com_vinculo[\s\S]*situacao/, "O Quadro de Gratificações deve permitir classificar os seis campos solicitados");
assert.match(app, /aria-sort[\s\S]*data-sort-grants[\s\S]*localeCompare/, "Os cabeçalhos classificáveis devem indicar a ordem e ordenar os registros");
assert.match(await readFile(resolve(root, "styles.css"), "utf8"), /\.sort-button[\s\S]*cursor:pointer/, "Os cabeçalhos classificáveis devem ter aparência de controle interativo");
assert.match(app, /data-remove-grant[\s\S]*Excluir[\s\S]*Excluir definitivamente esta gratificação/, "O quadro deve oferecer exclusão definitiva com confirmação explícita");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /from\("gratificacoes"\)\.delete\(\)[\s\S]*eq\("lock_version"/, "A exclusão deve respeitar a versão do registro");
const grantDeleteMigration = await readFile(resolve(root, "supabase-grant-delete-migration.sql"), "utf8");
assert.match(grantDeleteMigration, /gratificacoes_delete[\s\S]*for delete[\s\S]*public\.can_edit_scenario/, "O banco deve limitar a exclusão a competências editáveis");
assert.match(grantDeleteMigration, /grant delete on public\.gratificacoes to authenticated/, "O banco deve conceder a operação somente a usuários autenticados sujeitos ao RLS");
assert.match(app, /#summary-table[\s\S]*<tfoot>[\s\S]*Total pago[\s\S]*state\.summary\.totals\.paid4/, "A consolidação deve mostrar o total pago no rodapé da coluna financeira");
assert.match(await readFile(resolve(root, "styles.css"), "utf8"), /#summary-table tbody td[\s\S]*font-weight:750/, "Todos os valores da consolidação devem ser exibidos em negrito");
assert.match(app, /report-switcher"\)\.hidden = directCsjt/, "A página direta do Quadro CSJT não deve mostrar o seletor de relatórios");
assert.doesNotMatch(app, /money\([^\n]*,\s*4\)|maximumFractionDigits:\s*4/, "Valores e percentuais exibidos devem usar duas casas");
assert.match(app, /minimumFractionDigits:\s*2, maximumFractionDigits:\s*2/, "A formatação deve fixar exatamente duas casas");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /gratificacoesTodas:\s*gratificacoes\.data/, "O relatório deve receber gratificações ativas e inativas");
const recoveryTemplate = await readFile(resolve(root, "supabase-email-template-recovery.html"), "utf8");
assert.match(recoveryTemplate, /\{\{ \.Token \}\}/, "O e-mail deve apresentar o código para digitação manual");
assert.match(recoveryTemplate, /\?recovery=1/, "O link do e-mail deve abrir a tela sem validar o token");
assert.doesNotMatch(recoveryTemplate, /ConfirmationURL/, "O e-mail não deve conter link que consome o token automaticamente");
const inviteTemplate = await readFile(resolve(root, "supabase-email-template-invite.html"), "utf8");
assert.match(inviteTemplate, /\{\{ \.Token \}\}/, "O convite deve apresentar o código para digitação manual");
assert.match(inviteTemplate, /\?invite=1/, "O convite deve abrir diretamente a tela de primeiro acesso");
assert.doesNotMatch(inviteTemplate, /ConfirmationURL/, "O convite não deve conter link que consome o token automaticamente");
const deleteFunction = await readFile(resolve(root, "supabase/functions/delete-user/index.ts"), "utf8");
const inviteFunction = await readFile(resolve(root, "supabase/functions/invite-user/index.ts"), "utf8");
const updateFunction = await readFile(resolve(root, "supabase/functions/update-user/index.ts"), "utf8");
assert.doesNotMatch(inviteFunction, /allowedRoles[^\n]*auditor/, "A função de convite não deve aceitar Auditor");
assert.match(deleteFunction, /auth\.admin\.deleteUser\(userId, false\)/, "A conta deve ser excluída somente pela API administrativa");
assert.match(deleteFunction, /userId === authData\.user\.id/, "O administrador não pode excluir a própria conta");
assert.match(deleteFunction, /último administrador ativo não pode ser excluído/, "O último administrador ativo deve ser preservado");
assert.match(deleteFunction, /\.from\("audit_logs"\)\.insert/, "A exclusão deve ser registrada na auditoria");
assert.match(updateFunction, /callerProfile\?\.role !== "admin" \|\| !callerProfile\.ativo/, "A edição deve exigir um administrador ativo");
assert.match(updateFunction, /auth\.admin\.getUserById\(userId\)[\s\S]*auth\.admin\.updateUserById\(userId/, "A edição deve sincronizar a conta de autenticação pelo UUID");
assert.match(updateFunction, /email_confirm:\s*true/, "O novo e-mail deve ser confirmado administrativamente para acesso imediato");
assert.match(updateFunction, /último administrador ativo não pode ser inativado nem perder o perfil admin/, "A edição deve preservar o último administrador ativo");
assert.match(updateFunction, /operation:\s*"UPDATE_USER"/, "A edição deve registrar uma ação específica na auditoria");
assert.match(updateFunction, /rollbackError[\s\S]*não pôde ser restaurada automaticamente/, "Falhas parciais devem tentar reversão e informar eventual falha da reversão");
const profileMigration = await readFile(resolve(root, "supabase-user-profile-migration.sql"), "utf8");
assert.match(profileMigration, /unique index if not exists profiles_email_lower_unique[\s\S]*lower\(email\)/, "O banco deve impedir e-mails duplicados sem diferenciar maiúsculas de minúsculas");
const presence = await readFile(resolve(root, "presence.js"), "utf8");
assert.match(presence, /from\("user_presence"\)\.upsert/, "Cada sessão deve publicar heartbeat na tabela de presença");
assert.match(presence, /ONLINE_WINDOW_MS[\s\S]*\.gte\("last_seen", cutoff\)/, "A lista deve ignorar sessões sem heartbeat recente");
assert.match(presence, /identity\.profile\.role === "admin"/, "Somente o cliente administrador deve consultar a lista completa");
const adminMigration = await readFile(resolve(root, "supabase-admin-presence-migration.sql"), "utf8");
assert.match(adminMigration, /on delete set null/gi, "A exclusão deve preservar referências históricas");
assert.match(adminMigration, /user_presence_read[\s\S]*public\.is_admin\(\)/, "Somente administradores podem ler a presença de outros usuários");
assert.match(adminMigration, /user_presence_insert[\s\S]*user_id = auth\.uid\(\)[\s\S]*public\.is_reader\(\)/, "Somente usuários ativos podem publicar a própria presença");
assert.match(adminMigration, /drop policy if exists presence_active_user_track on realtime\.messages/, "A política defeituosa do canal Realtime deve ser removida");
const accessMigration = await readFile(resolve(root, "supabase-access-ui-migration.sql"), "utf8");
assert.match(accessMigration, /set role = 'consulta' where role = 'auditor'/, "Auditores existentes devem migrar com segurança para Consulta");
assert.match(accessMigration, /audit_read[\s\S]*public\.is_admin\(\)/, "Somente Admin pode ler a auditoria");
assert.match(accessMigration, /clear_audit_logs[\s\S]*public\.is_admin\(\)/, "A limpeza deve validar o perfil Admin no banco");
assert.match(accessMigration, /delete from public\.audit_logs where id is not null;/, "A limpeza deve usar um filtro explicito compativel com a protecao contra DELETE sem WHERE");
assert.doesNotMatch(accessMigration, /delete from public\.audit_logs\s*;/, "A limpeza nao pode executar DELETE sem WHERE");
const setupSql = await readFile(resolve(root, "supabase-setup.sql"), "utf8");
assert.match(setupSql, /delete from public\.audit_logs where id is not null;/, "A instalacao completa deve conter a correcao da limpeza de auditoria");
assert.doesNotMatch(setupSql, /delete from public\.audit_logs\s*;/, "A instalacao completa nao pode recriar o DELETE sem WHERE");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /rpc\("clear_audit_logs"\)/, "A limpeza deve usar a função protegida do banco");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /referencias_financeiras_detalhadas/, "Admin e Gestor devem carregar as referências por competência");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /rpc\("save_financial_references"/, "Referências devem ser salvas pela função protegida do banco");
const referencesMigration = await readFile(resolve(root, "supabase-references-migration.sql"), "utf8");
const historyMigration = await readFile(resolve(root, "supabase-history-migration.sql"), "utf8");
assert.match(referencesMigration, /create table if not exists public\.referencias_financeiras/, "A migração deve versionar referências por competência");
assert.match(referencesMigration, /referencias_read[\s\S]*public\.is_writer\(\)/, "Somente Admin e Gestor podem consultar referências diretamente");
assert.match(referencesMigration, /save_financial_references[\s\S]*Somente administradores e gestores/, "O banco deve proteger a gravação das referências");
assert.match(referencesMigration, /audit_referencias[\s\S]*public\.audit_change\(\)/, "Alterações nas referências devem entrar na Auditoria");
assert.match(referencesMigration, /default \.65/, "O percentual padrão deve ser 65%");
assert.match(referencesMigration, /current_view in \([^)]*'referencias'/, "A presença deve aceitar a página Referências");
assert.match(app, /linkedValueFromPercent/, "O valor com vínculo deve usar cálculo decimal seguro");
assert.match(historyMigration, /lineage_id[\s\S]*gratificacoes_cenario_lineage_unique/, "Cada gratificação deve manter identidade entre competências");
assert.match(historyMigration, /p_copy_grants[\s\S]*insert into public\.gratificacoes/, "A cópia integral deve ser transacional no banco");
assert.match(historyMigration, /p_data_complete[\s\S]*dados_individualizados_completos/, "A completude histórica deve ser persistida no banco");
assert.match(historyMigration, /lock_version[\s\S]*old\.lock_version \+ 1/, "Edições concorrentes devem usar versão otimista");
assert.match(historyMigration, /can_edit_scenario[\s\S]*status in \('RASCUNHO','VIGENTE'\)/, "Competências encerradas não podem aceitar alterações");
assert.match(historyMigration, /left join public\.referencias_financeiras r[\s\S]*r\.cenario_id=g\.cenario_id/, "Cada snapshot deve usar seus próprios parâmetros financeiros");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /eq\("lock_version"/, "O frontend deve detectar conflito de concorrência");
assert.match(app, /LIMPAR AUDITORIA[\s\S]*clearAuditLogs\(\)/, "A limpeza deve exigir confirmação explícita");
const palette = new Set(["#01426A","#0067A0","#007B5F","#00B388","#FFCD00","#FBDB65"]);
const visualSources = `${app}\n${await readFile(resolve(root, "styles.css"), "utf8")}\n${await readFile(resolve(root, "reports.css"), "utf8")}`;
for (const color of palette) assert.match(visualSources, new RegExp(color, "i"), `A paleta deve conter ${color}`);
for (const color of visualSources.match(/#[0-9a-f]{6}\b/gi) ?? []) assert.ok(palette.has(color.toUpperCase()), `Cor fora da paleta institucional: ${color}`);
assert.match(combined, /Deno\.env\.get\("SUPABASE_SERVICE_ROLE_KEY"\)/, "A função deve obter a chave administrativa somente do ambiente protegido");
console.log(`Referências estáticas validadas: ${refs.join(", ")}.`);
