import assert from "node:assert/strict";
import { readFile, access } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const html = await readFile(resolve(root, "index.html"), "utf8");
const refs = [...html.matchAll(/(?:src|href)="(\.\/[^"?#]+)"/g)].map(match => match[1]);
for (const ref of refs) await access(resolve(root, ref.slice(2)));
const all = await Promise.all(["index.html","app.js","auth.js","data-service.js","supabase-client.js","app-config.js","styles.css","reports.css","supabase-email-template-recovery.html","supabase-email-template-invite.html","supabase-setup.sql","supabase-seed.sql","supabase/functions/invite-user/index.ts",".nojekyll",".github/workflows/pages.yml"].map(file => readFile(resolve(root,file),"utf8")));
const combined = all.join("\n");
assert.doesNotMatch(combined, /sb_secret_[a-zA-Z0-9_-]+/i);
assert.doesNotMatch(combined, /serviceRoleKey\s*:\s*["'][^"']+/i);
assert.doesNotMatch(combined, /eyJ[a-zA-Z0-9_-]{20,}\.[a-zA-Z0-9_-]{20,}\.[a-zA-Z0-9_-]{20,}/);
assert.match(await readFile(resolve(root,".github/workflows/pages.yml"),"utf8"), /actions\/deploy-pages@v4/);
const auth = await readFile(resolve(root, "auth.js"), "utf8");
const app = await readFile(resolve(root, "app.js"), "utf8");
const htmlIds = new Set([...html.matchAll(/\bid="([A-Za-z0-9_-]+)"/g)].map(match => match[1]));
const referencedIds = new Set([...app.matchAll(/\$\("#([A-Za-z0-9_-]+)"\)/g)].map(match => match[1]));
for (const id of referencedIds) assert.ok(htmlIds.has(id), `O seletor #${id} do JavaScript deve existir no HTML`);
assert.match(auth, /\.eq\("id",\s*session\.user\.id\)\s*\.single\(\)/s, "A consulta do perfil deve ficar restrita ao usuário autenticado");
assert.match(auth, /updateUser\(\{ password \}\)/, "A recuperação deve permitir cadastrar a nova senha");
assert.match(auth, /verifyOtp\(\{[\s\S]*type,/, "O código deve ser validado com o tipo do fluxo de acesso");
assert.match(auth, /\["invite", "recovery"\]\.includes\(type\)/, "Somente convite e recuperação podem validar códigos de acesso");
assert.match(html, /id="password-recovery-form"/, "A página deve conter o formulário de nova senha");
assert.match(html, /id="recovery-code-form"[\s\S]*autocomplete="one-time-code"/, "A página deve permitir validar manualmente o código de recuperação");
assert.match(html, /id="first-access"[\s\S]*Primeiro acesso \/ cadastrar senha/, "O login deve oferecer cadastro da primeira senha");
assert.match(html, /id="user-form"[\s\S]*name="role"/, "A administração deve conter cadastro de usuário e perfil");
assert.match(html, /\[hidden\]\s*\{\s*display:\s*none\s*!important\s*\}/, "Telas ocultas não podem ser reexibidas pelo CSS de layout");
assert.match(await readFile(resolve(root, "app.js"), "utf8"), /PASSWORD_RECOVERY[\s\S]*otp_expired|otp_expired[\s\S]*PASSWORD_RECOVERY/, "A aplicação deve tratar recuperação e links expirados");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /functions\.invoke\("invite-user"/, "O cadastro deve usar a função protegida de convite");
assert.match(html, /id="report-field-options"[\s\S]*id="report-active"|id="report-active"[\s\S]*id="report-field-options"/, "O relatório deve permitir escolher campos e incluir inativas");
assert.match(html, /id="show-custom-report"[\s\S]*id="show-csjt-report"/, "Relatório customizável e Quadro CSJT devem compartilhar o seletor de relatórios");
assert.match(html, /id="report-title"[\s\S]*id="report-group"[\s\S]*id="report-order"[\s\S]*id="report-direction"/, "O relatório deve permitir título, agrupamento e ordenação");
assert.match(html, /id="csjt-report-view"[\s\S]*id="csjt-sheet"/, "O Quadro CSJT deve existir como relatório próprio");
assert.doesNotMatch(html, /SIMULAÇÕES|Incremento efetivos/i, "O Quadro CSJT não deve reproduzir a simulação da página de referência");
assert.match(await readFile(resolve(root, "app.js"), "utf8"), /summarizeCsjt\(state\.data\.gratificacoesTodas/, "O Quadro CSJT deve ser calculado com os dados carregados da aplicação");
assert.match(await readFile(resolve(root, "app.js"), "utf8"), /csjtSection\("Situação Anterior"[\s\S]*csjtSection\("Situação Atual"/, "O Quadro CSJT deve apresentar as situações anterior e atual nessa ordem");
assert.match(await readFile(resolve(root, "reports.css"), "utf8"), /\.csjt-bottom[\s\S]*\.info-value[\s\S]*body\.printing-csjt/, "O Quadro CSJT deve manter os quadros inferiores e a impressão da referência");
assert.match(app, /updateNewGrantVisibility\(button\.dataset\.view\)/, "Nova gratificação deve acompanhar a seção ativa");
assert.match(app, /activeView === "gratificacoes"/, "Nova gratificação deve aparecer somente em Gratificações");
assert.match(await readFile(resolve(root, "data-service.js"), "utf8"), /gratificacoesTodas:\s*gratificacoes\.data/, "O relatório deve receber gratificações ativas e inativas");
const recoveryTemplate = await readFile(resolve(root, "supabase-email-template-recovery.html"), "utf8");
assert.match(recoveryTemplate, /\{\{ \.Token \}\}/, "O e-mail deve apresentar o código para digitação manual");
assert.match(recoveryTemplate, /\?recovery=1/, "O link do e-mail deve abrir a tela sem validar o token");
assert.doesNotMatch(recoveryTemplate, /ConfirmationURL/, "O e-mail não deve conter link que consome o token automaticamente");
const inviteTemplate = await readFile(resolve(root, "supabase-email-template-invite.html"), "utf8");
assert.match(inviteTemplate, /\{\{ \.Token \}\}/, "O convite deve apresentar o código para digitação manual");
assert.match(inviteTemplate, /\?invite=1/, "O convite deve abrir diretamente a tela de primeiro acesso");
assert.doesNotMatch(inviteTemplate, /ConfirmationURL/, "O convite não deve conter link que consome o token automaticamente");
assert.match(combined, /Deno\.env\.get\("SUPABASE_SERVICE_ROLE_KEY"\)/, "A função deve obter a chave administrativa somente do ambiente protegido");
console.log(`Referências estáticas validadas: ${refs.join(", ")}.`);
